version: "3.4"

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    entrypoint: /usr/src/bin/dev-entrypoint.sh
    volumes:
      - .:/usr/src
