version: "3.4"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:10.3-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data
    # Mount the database init scripts:
    - ./db_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 3x4mpl3
    deploy:
      placement:
        constraints: [node.role == manager]

  web:
    image: vovimayhem/real-world-backend-django
    ports:
    - published: 5000
      target: 8000
    depends_on:
    - postgres
    environment:
      DATABASE_URL: postgres://postgres:3x4mpl3@postgres:5432/demo_development
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
